#!/usr/bin/env python3
"""Generate deploy/migrations/011_backfill_movement_muscles.sql from tagged MOVEMENTS.

Produces one idempotent guarded UPDATE per movement:
    UPDATE movement SET primary_muscle='X', secondary_muscles='[...]'
      WHERE name='...' AND primary_muscle IS NULL;

The AND primary_muscle IS NULL guard ensures re-running the migration is safe.

Run from the repo root:
    python scripts/gen_muscle_backfill.py
"""
import json
from pathlib import Path
from ironlog.seed import MOVEMENTS

output_path = Path("deploy/migrations/011_backfill_movement_muscles.sql")

lines = [
    "-- 011_backfill_movement_muscles.sql",
    "-- Backfill primary_muscle and secondary_muscles for all 108 library movements.",
    "-- Idempotent: each UPDATE is guarded by AND primary_muscle IS NULL.",
    "-- Generated by scripts/gen_muscle_backfill.py — do not edit by hand.",
    "",
]

missing = []
for m in MOVEMENTS:
    name = m["name"]
    primary = m.get("primary_muscle")
    secondary = m.get("secondary_muscles", [])

    if primary is None:
        missing.append(name)
        continue

    # Escape single quotes in name for SQL (e.g. apostrophes)
    name_sql = name.replace("'", "''")
    sec_json = json.dumps(secondary)

    lines.append(
        f"UPDATE movement SET primary_muscle='{primary}', secondary_muscles='{sec_json}' "
        f"WHERE name='{name_sql}' AND primary_muscle IS NULL;"
    )

if missing:
    raise ValueError(f"Movements still untagged: {missing}")

output_path.write_text("\n".join(lines) + "\n")
print(f"Generated {output_path} with {len(MOVEMENTS)} UPDATE statements.")
